Add Run Number Option to ADARA Retranslate Manual 	- for Ray's needs on SNAP/Imaging Runs, which sometimes 	"succeed" in terms of NeXus file generation and Image file copies, 	but actually "missed a few" Image files in the end, lol... ;-D 	- added Run Number command line options a la ADARA Fix IPTS: 		-> --run=<RunNumber1> 		-> --run=<RunNumber2,RunNumber3,...> 		-> --run=<RunNumber4-RunNumber5> 	- stole PARSE_RUN_NUMBERS() function from ADARA Fix IPTS... ;-D 	- created 2 basic modes of operation: 		-> Generate Raw Data Directories from Run Number List 		-> Check for "Manual Processing Required" Token Files 	- collect set of Raw Data Directories and proceed as before... :-) 	- while I was at it, also cleaned up the STC Host/Service stuff 		-> distinguish between the "--opt" command line options 		that are passed down into ADARA Add Run End verbatim, 		and the relevant actual extracted STC Host/Service "Names" 		-> likewise, actually update "Default STC Host" to use the 		STC Host to query for STC Service Ports, as applicable... 			=> not that we can ever SSH from DAQ1 to STC... ;-b 		-> for yuks & odd testing, added ADARA Test Harness options 			=> --stc_devel and --stc_master 	- It Appears to Work! ;-D

diff --git a/sms/adara_retranslate_manual b/sms/adara_retranslate_manual
--- a/sms/adara_retranslate_manual
+++ b/sms/adara_retranslate_manual
@@ -14,7 +14,8 @@ ADARA_ADD_RUN_END="/usr/local/bin/adara_add_run_end"
 
 ADARA_PARSER="/usr/local/bin/adara-parser"
 
-DEFAULT_STC_HOST="stc1.ornl.gov"
+DEFAULT_STC_HOST_DOMAIN="ornl.gov"
+DEFAULT_STC_HOST="stc1.${DEFAULT_STC_HOST_DOMAIN}"
 
 XINETD_DIR="/etc/xinetd.d"
 
@@ -32,6 +33,7 @@ TAIL="/usr/bin/tail"
 AWK="/usr/bin/awk"
 SSH="/usr/bin/ssh"
 GREP="/bin/grep"
+SED="/bin/sed"
 LS="/bin/ls"
 
 USAGE()
@@ -40,14 +42,70 @@ USAGE()
 	echo "    [--inst=<INST>] [--facility=<SNS|HFIR>] \\"
 	echo "    [--stc1|--stc2|--stc_host=<STC_HOST>] \\"
 	echo "    [--stc|--stc_test|--stc_dummy|--stc_hfir|--stc_hfir_test] \\"
+	echo "    [--stc_devel|--stc_master] (ADARA Test Harness Use Only) \\"
 	echo "    [--stc_port=<STCPort>] \\"
 	echo "    [--adara_add_run_end=<${ADARA_ADD_RUN_END}>] \\"
 	echo "    [--adara_parser=<${ADARA_PARSER}>] \\"
 	echo "    [--alt=\"-mon\"] \\"
 	echo "    [--sms_data=<${SMS_DATA}>] \\"
 	echo "    [--sms_log=<${SMS_LOG}>] \\"
+	echo "    [--run=<RunNumber1>] \\"
+	echo "    [--run=<RunNumber2,RunNumber3,...>] \\"
+	echo "    [--run=<RunNumber4-RunNumber5>] \\"
 	echo "    [--help|-h]"
 	echo
+}
+
+PARSE_RUN_NUMBERS()
+{
+	local _runlist="$1"
+
+	echo -e "\nParsing Run Numbers: [${_runlist}]"
+
+	# Strip Off Any Comma Separators...
+	_runlist=`echo "${_runlist}" | ${SED} 's/,/ /g'`
+	cksed=$?
+
+	if [[ ${cksed} != 0 ]]; then
+		echo -e "\nERROR Parsing Comma-Separated Run Number List...!"
+		echo -e "\nBailing..."
+		exit 111
+	fi
+
+	# Step Through Run Numbers Looking for Any Run Number Ranges
+	local _runlistall
+	local _run
+	for _run in ${_runlist} ; do
+		# Run Number Range
+		if [[ "${_run}" =~ - ]]; then
+			local _start
+			local _end
+			_start=`echo "${_run}" | ${AWK} -F "-" '{print $1}'`
+			_end=`echo "${_run}" | ${AWK} -F "-" '{print $2}'`
+			for (( i = _start ; i <= _end ; ++i )); do
+				if [[ -z "${_runlistall}" ]]; then
+					_runlistall="$i"
+				else
+					_runlistall="${_runlistall} $i"
+				fi
+			done
+		# Plain Run Number
+		else
+			if [[ -z "${_runlistall}" ]]; then
+				_runlistall="${_run}"
+			else
+				_runlistall="${_runlistall} ${_run}"
+			fi
+		fi
+	done
+
+	# Now Append Parsed Run Number List to Overall Run List
+	if [[ -z "${RUN_NUMBERS}" ]]; then
+		RUN_NUMBERS="${_runlistall}"
+	else
+		RUN_NUMBERS="${RUN_NUMBERS} ${_runlistall}"
+	fi
+	echo -e "\nAdding Run Number(s) ${_runlistall} to Run List."
 }
 
 CHECK_PROCEED()
@@ -86,6 +144,8 @@ STC_HOST=""
 
 STC_PORT=""
 
+RUN_NUMBERS=""
+
 for arg in "$@" ; do
 
 	key=`echo "$arg" | ${AWK} -F = '{print $1}'`
@@ -110,24 +170,31 @@ for arg in "$@" ; do
 	elif [[ "#$key#" == '#--stc1#' || "#$key#" == '#--stc2#' ]]; then
 		STC_HOST="${key}"
 		echo -e "\nSetting STC Host to: ${STC_HOST}"
+		STC_HOST_NAME=`echo "${STC_HOST}" | ${SED} 's/^--//'`
+		DEFAULT_STC_HOST="${STC_HOST_NAME}.${DEFAULT_STC_HOST_DOMAIN}"
 	elif [[ "#$key#" == '#--stc_host#' ]]; then
 		STC_HOST="${key}=${value}"
-		echo -e "\nSetting STC Host to: ${STC_HOST}"
+		STC_HOST_NAME="$value"
+		echo -e "\nSetting STC Host to: ${STC_HOST_NAME}"
+		DEFAULT_STC_HOST="${STC_HOST_NAME}"
 	elif [[ "#$key#" == '#--stc#' || "#$key#" == '#--stc_test#'
 			|| "#$key#" == '#--stc_dummy#'
 			|| "#$key#" == '#--stc_hfir#'
-			|| "#$key#" == '#--stc_hfir_test#' ]]; then
+			|| "#$key#" == '#--stc_hfir_test#'
+			|| "#$key#" == '#--stc_devel#'
+			|| "#$key#" == '#--stc_master#' ]]; then
 		STC_SERVICE="${key}"
-		echo -e "\nSetting STC Service to: ${STC_SERVICE}"
+		STC_SERVICE_NAME=`echo "${STC_SERVICE}" | ${SED} 's/^--//'`
+		echo -e "\nSetting STC Service to: ${STC_SERVICE_NAME}"
 		echo -e "\nContacting STC Host \"${DEFAULT_STC_HOST}\" via SSH"
-		echo "to Determine Port for STC \"${STC_SERVICE}\" Service..."
+		echo "   to Get Port for STC \"${STC_SERVICE_NAME}\" Service..."
 		echo -e -n "\n${SSH} ${DEFAULT_STC_HOST}"
-		echo -e " ${GREP} port ${XINETD_DIR}/${STC_SERVICE}"
+		echo -e " ${GREP} port ${XINETD_DIR}/${STC_SERVICE_NAME}"
 		STC_PORT=`${SSH} ${DEFAULT_STC_HOST} \
-			${GREP} "port" ${XINETD_DIR}/${STC_SERVICE} \
+			${GREP} "port" ${XINETD_DIR}/${STC_SERVICE_NAME} \
 			| ${AWK} '{print $3}'`
-		echo -e \
-			"\nGot STC Port ${STC_PORT} for STC \"${STC_SERVICE}\" Service."
+		echo -e -n "\nGot STC Port ${STC_PORT}"
+		echo -e " for STC \"${STC_SERVICE_NAME}\" Service."
 	elif [[ "#$key#" == '#--stc_port#' ]]; then
 		STC_PORT="$value"
 		echo -e "\nSetting STC Port to: ${STC_PORT}"
@@ -153,6 +220,8 @@ for arg in "$@" ; do
 	elif [[ "#$key#" == '#--sms_log#' ]]; then
 		SMS_LOG="${value}"
 		echo -e "\nSetting SMS Log File to:\n\t[${SMS_LOG}]"
+	elif [[ "#$key#" == '#--run#' ]]; then
+		PARSE_RUN_NUMBERS "${value}"
 	elif [[ "#$key#" == '#--help#' || "#$key#" == '#-h#' ]]; then
 		USAGE
 		exit 0
@@ -170,17 +239,75 @@ if [[ -z "${INST}" ]]; then
 	exit 2
 fi
 
+# Generate List of Raw Data Directories...
+
+DIRS=""
+
+# Generate Raw Data Directories from Run Number List...
+
+if [[ -n "${RUN_NUMBERS}" ]]; then
+
+	echo -e "\nGenerating Raw Data Directories from Run Number List..."
+
+	echo -e "\n   [${RUN_NUMBERS}]"
+
+	for run in ${RUN_NUMBERS} ; do
+
+		echo -e "\nLooking for Run ${run}:"
+
+		dir=`${LS} -d ${SMS_DATA}/2*/*run*${run}/`
+
+		if [[ $? != 0 ]]; then
+			echo -e "\nError Finding Raw Data Directory for Run ${run}!"
+			CHECK_PROCEED
+			if [[ $? != 0 ]]; then
+				echo -e \
+				"\nExiting ADARA Retranslate Manual at User's Request.\n"
+				exit 0
+			fi
+		else
+			echo -e "\nFound Raw Data Directory for Run ${run}:"
+			echo -e "\n   [${dir}]"
+			DIRS="${DIRS} ${dir}"
+		fi
+
+	done
+
 # Check for "Manual Processing Required" Token Files...
 
-MANS=`${LS} ${SMS_DATA}/2*/*run*/man*`
+else
 
-for man in ${MANS} ; do
+	echo -e "\nChecking for \"Manual Processing Required\" Token Files..."
 
-	echo -e "\n$man"
+	MANS=`${LS} ${SMS_DATA}/2*/*run*/man*`
 
-	dir=`${DIRNAME} ${man}`
+	for man in ${MANS} ; do
 
-	echo -e "\ndir=[$dir]"
+		echo -e "\n$man"
+
+		dir=`${DIRNAME} ${man}`
+
+		echo -e "\ndir=[$dir]"
+
+		DIRS="${DIRS} ${dir}"
+
+	done
+
+fi
+
+# Process Raw Data Directories...
+
+if [[ -n "${DIRS}" ]]; then
+	echo -e "\nProcessing Collected Raw Data Directories in Turn:"
+else
+	echo -e "\nWarning: No Raw Data Directories Found!"
+	echo -e "\nBailing...\n"
+	exit -1
+fi
+
+for dir in ${DIRS} ; do
+
+	echo -e "\n$dir"
 
 	echo
 	${LS} -lt $dir | ${HEAD}
@@ -196,7 +323,7 @@ for man in ${MANS} ; do
 
 	echo -e "\nfile=[$basefile]"
 
-	CHECK_PROCEED "Continue"
+	CHECK_PROCEED "Continue with This Run..."
 
 	if [[ $? == 0 ]]; then
 
@@ -221,7 +348,15 @@ for man in ${MANS} ; do
 
 				pushd $dir
 
-				/bin/rm manual_processing_needed
+				if [[ -f manual_processing_needed ]]; then
+					echo -e "\nRemoving manual_processing_needed Marker."
+					/bin/rm manual_processing_needed
+				fi
+
+				if [[ -f translation_completed ]]; then
+					echo -e "\nRemoving translation_completed Marker."
+					/bin/rm translation_completed
+				fi
 
 				caput -S ${BL}:SMS:StorageManager:RescanRunDir `pwd`
 
@@ -244,4 +379,6 @@ for man in ${MANS} ; do
 	fi
 
 done
+
+echo -e "\nDone.\n"
 
