(Finally) Finished Base "NoMulti" Multi Meta-Data! 	- in ADARA "Fix IPTS" Script... 		-> completed partial changes from back in _April_...! ;-D 	- replaced generic XML Tag search in LOOKUP_PROPOSAL_METADATA() 	with more specific "grep -n" (to get _Line Numbers_ with results) 		-> renamed global "$ipts_old_line" to "$ipts_old_line_wnum" 		-> allow capture of Multiple Meta-Data lines, even w/NoMulti 			=> use ${SMS_WHICH_DATA_FILE} to 			Choose First/Last *Line* out of those retrieved... 		-> save/extract/utilize Line Number along with Old IPTS Line 		to be more "surgical" in which line gets substituted later 		in UPDATE_PROPOSAL_METADATA()... 		-> It Works...! ;-D 	- also, cleaned up some basic output logging for consistency... 		-> added explicit logging of ${SMS_WHICH_DATA_FILE} setting 		(i.e. "FIRST" or "LAST") in the startup message...

diff --git a/sms/adara_fix_ipts b/sms/adara_fix_ipts
--- a/sms/adara_fix_ipts
+++ b/sms/adara_fix_ipts
@@ -323,7 +323,9 @@ fi
 #
 
 echo -e "\n*** Updating IPTS for Run Numbers:\n\n\t[${RUN_NUMBERS}]\n"
-echo "to New Proposal [${IPTS_NEW}]."
+echo "to New Proposal [${IPTS_NEW}],"
+
+echo -e "\nby Editing ${SMS_WHICH_DATA_FILE} Data File,"
 
 echo -e -n "\nUsing STS \"${STS_SERVICE}\" Service "
 echo "on \"${STS_HOST}:${STS_PORT}\"."
@@ -785,7 +787,7 @@ MANUAL_EDIT()
 
 	# Copy Original Data File to New Copy for Editing...
 
-	echo -e -n "\nCopying ${SMS_WHICH_DATA_FILE} ADARA Output Stream File "
+	echo -e "\nCopying ${SMS_WHICH_DATA_FILE} ADARA Output Stream File "
 	echo "for Editing Run ${run}:"
 	echo -e "\t[${_datafile}]"
 	echo -e "\t->[${_datafile}.NEW-$$]"
@@ -901,14 +903,16 @@ LOOKUP_PROPOSAL_METADATA()
 	# _Not_ of the form "IPTS-*"... ;-D
 	#
 
-	# Note: Global Reference to "$ipts_old_line"...! ;-D
-	ipts_old_line=`${GREP} --text "<${_xml_tag}>" "${rundir}/${datafile}"`
+	# Note: Global Reference to "$ipts_old_line_wnum"...! ;-D
+	ipts_old_line_wnum=`${GREP} --text -n "<${_xml_tag}>" \
+		"${rundir}/${datafile}"`
 	ckoldiptsline=$?
 
 	if [[ ${ckoldiptsline} != 0 ]]; then
 		echo -e -n "\nERROR Extracting Old ${_meta_name} Line "
-		echo -e "from Stream File for Run ${run}!\n"
-		echo -e "\t[${ipts_old_line}]"
+		echo "from Stream File for Run ${run}!"
+		echo -e "\n\t[${ipts_old_line_wnum}]"
+		### TODO: Try the "2nd" or "Next to Last" File...?
 		MANUAL_EDIT "${rundir}" "${datafile}" \
 			"${_xml_tag}" "${_meta_name}" "${_new_value}"
 		if [[ $? != 0 ]]; then
@@ -920,32 +924,51 @@ LOOKUP_PROPOSAL_METADATA()
 		fi
 	fi
 
-	# Make Sure We Only Got *1* Old Proposal Meta-Data Line...! ;-D
-	ckoneline=`echo "${ipts_old_line}" | ${WC} | ${AWK} '{print $1}'`
+	# See How Many Old Proposal Meta-Data Lines We Got...
+	ckoneline=`echo "${ipts_old_line_wnum}" \
+		| ${WC} | ${AWK} '{print $1}'`
 
+	# Make Sure We Only Get *1* Old Proposal Meta-Data Line...! ;-D
 	if [[ "${_allow_multi}" == "NoMulti" ]]; then
+
+		# Oops, Got More Than 1 Meta-Data Line...
 		if [[ ${ckoneline} != 1 ]]; then
-			echo -e -n "\nERROR: Multiple ${_meta_name} Lines Found "
-			echo -e "for Run ${run}!\n"
-			echo -e "${ipts_old_line}"
-			MANUAL_EDIT "${rundir}" "${datafile}" \
-				"${_xml_tag}" "${_meta_name}" "${_new_value}"
-			if [[ $? != 0 ]]; then
-				CHECK_PROCEED
-				echo -e "\nContinuing with Next Run Number..."
-				return 31
+
+			echo -e -n "\nWarning: Multiple ${_meta_name} Lines Found "
+			echo "for Run ${run}!"
+			echo -e "\n${ipts_old_line_wnum}"
+				# Allow Self-Indenting from XML Line(s)
+
+			# Take First Line of the First Data File...
+			if [[ "${SMS_WHICH_DATA_FILE}" == "FIRST" ]]; then
+				ipts_old_line_wnum=`echo "${ipts_old_line_wnum}" \
+					| ${HEAD} -1`
+				echo -e -n "\nUsing First ${_meta_name} "
+				echo "of the First Data File for Run ${run}:"
+				echo -e "\n${ipts_old_line_wnum}"
+					# Allow Self-Indenting from XML Line(s)
+			# Else Take Last Line of the Last Data File...
 			else
-				return 255   # Pass-Thru Return...!
+				ipts_old_line_wnum=`echo "${ipts_old_line_wnum}" \
+					| ${TAIL} -1`
+				echo -e -n "\nUsing Last ${_meta_name} "
+				echo "of the Last Data File for Run ${run}:"
+				echo -e "\n${ipts_old_line_wnum}"
+					# Allow Self-Indenting from XML Line(s)
 			fi
+
 		fi
+
+	# Take 'Em All, We're Ok with Multiple Meta-Data Lines...
 	else
 		echo -e "\nLookup Found ${ckoneline} Results."
 	fi
 
-	echo -e "\nFound Old ${_meta_name} Line(s) for Run ${run}:"
-	echo -e "\n${ipts_old_line}"   # Allow Self-Indenting from XML Line(s)
+	echo -e "\nOld ${_meta_name} Line(s) for Run ${run}:"
+	echo -e "\n${ipts_old_line_wnum}"
+		# Allow Self-Indenting from XML Line(s)
 
-	local _old_value=`echo "${ipts_old_line}" \
+	local _old_value=`echo "${ipts_old_line_wnum}" \
 		| ${AWK} -F "[<>]" '{print $3}'`
 	ckoldipts=$?
 
@@ -1021,6 +1044,54 @@ UPDATE_PROPOSAL_METADATA()
 	fi
 
 	#
+	# Separate Old Meta-Data Line into Line Number and Content...
+	#
+
+	ipts_old_line_num=`echo "${ipts_old_line_wnum}" \
+		| ${AWK} -F ":" '{print $1}'`
+	ckawkoldlinenum=$?
+
+	if [[ ${ckawkoldlinenum} != 0 ]]; then
+		echo -e -n "\nERROR Extracting Line Number from "
+		echo "${_meta_name} Meta-Data Line...!"
+		MANUAL_EDIT "${rundir}" "${datafile}" \
+			"${_xml_tag}" "${_meta_name}" "${_new_value}"
+		if [[ $? != 0 ]]; then
+			CHECK_PROCEED
+			echo -e "\nContinuing with Next Run Number..."
+			return 33
+		else
+			return 0
+		fi
+	fi
+
+	ipts_old_line=`echo "${ipts_old_line_wnum}" \
+		| ${AWK} -F ":" '{print $2}'`
+	ckawkoldline=$?
+
+	if [[ ${ckawkoldline} != 0 ]]; then
+		echo -e -n "\nERROR Extracting Content from "
+		echo "${_meta_name} Meta-Data Line...!"
+		MANUAL_EDIT "${rundir}" "${datafile}" \
+			"${_xml_tag}" "${_meta_name}" "${_new_value}"
+		if [[ $? != 0 ]]; then
+			CHECK_PROCEED
+			echo -e "\nContinuing with Next Run Number..."
+			return 34
+		else
+			return 0
+		fi
+	fi
+
+	echo -e -n "\nExtracted Line Number and Content "
+	echo "from ${_meta_name} Meta-Data Line:"
+	echo -e "\n\t${ipts_old_line_wnum}\n"
+		# Allow Self-Indenting from XML Line(s)
+	echo -e "\t-> Line #${ipts_old_line_num}"
+	echo -e "\t-> [${ipts_old_line}]"
+		# Allow Self-Indenting from XML Line(s)
+
+	#
 	# Compare the *Length* of the Old and New Proposal Meta-Data,
 	# to Carefully Determine How We Handle the Substitution
 	# Without _Changing the Size_ of the XML Payload in the
@@ -1065,7 +1136,7 @@ UPDATE_PROPOSAL_METADATA()
 		echo -e "\nResulting New ${_meta_name} is: [${_new_value}]"
 
 	# If New Meta-Data is _Longer_ than Old Meta-Data,
-	# Just Pad with White Space...
+	# Try to Remove Sufficient White Space...
 	elif [[ ${#_new_value} -gt ${#update_old_value} ]]; then
 
 		len_diff=$(( ${#_new_value} - ${#update_old_value} ))
@@ -1082,7 +1153,7 @@ UPDATE_PROPOSAL_METADATA()
 		for (( i = 0 ; i < ${len_diff} ; ++i )); do
 
 			ckspc=`echo "${ipts_new_line}" | ${GREP} -c " "`
-			if [[ "${ckspc}" != "1" ]]; then
+			if [[ "${ckspc}" != "1" ]]; then   # Not 1 Line Found...
 				echo -e -n "\nERROR: Insufficient White Space to Remove "
 				echo "in Old ${_meta_name} Line!"
 				MANUAL_EDIT "${rundir}" "${datafile}" \
@@ -1120,12 +1191,13 @@ UPDATE_PROPOSAL_METADATA()
 
 		# Skip This Run, We Had a Failure...
 		if [[ $skip_run == 1 ]]; then
-			return 33
+			return 35
 		fi
 
 		echo -e "\nResulting New/Old ${_meta_name} Line Template is:"
 		echo -e "\t[${ipts_new_line}]"
 
+	# New Meta-Data is _Same_ Length as Old Meta-Data, Yay! ;-D
 	else
 
 		echo -e -n "\nNew ${_meta_name} [${_new_value}] is "
@@ -1150,7 +1222,7 @@ UPDATE_PROPOSAL_METADATA()
 		if [[ $? != 0 ]]; then
 			CHECK_PROCEED
 			echo -e "\nContinuing with Next Run Number..."
-			return 34
+			return 36
 		else
 			return 0
 		fi
@@ -1158,15 +1230,20 @@ UPDATE_PROPOSAL_METADATA()
 
 	echo -e "\nFinal ${_meta_name} Line Substitution:"
 	echo -e "\told: [${ipts_old_line}]"
+		# Allow Self-Indenting from XML Line(s)
 	echo -e "\tnew: [${ipts_new_line}]"
+		# Allow Self-Indenting from XML Line(s)
 
 	CHECK_PROCEED
 
 	#
 	# Append Substitution to List
+	# (Using Specific Line Number from Selected Old Meta-Data Line!)
 	#
 
-	SUBST_EXPRS="$SUBST_EXPRS -e \"s@${ipts_old_line}@${ipts_new_line}@\""
+	subst="${ipts_old_line_num}s@${ipts_old_line}@${ipts_new_line}@"
+
+	SUBST_EXPRS="$SUBST_EXPRS -e \"${subst}\""
 
 	#
 	# Set/Save Old Value Global, If Specified...
@@ -1239,8 +1316,8 @@ for run in ${RUN_NUMBERS} ; do
 
 	if [[ ${ckone} != 1 ]]; then
 		echo -e -n "\nERROR: Multiple Output Stream Files Found "
-		echo -e "for Run ${run}!\n"
-		echo -e "${datafile}\n"
+		echo "for Run ${run}!"
+		echo -e "\n${datafile}\n"
 		CHECK_PROCEED
 		echo -e "\nContinuing with Next Run Number..."
 		continue
@@ -1375,6 +1452,7 @@ for run in ${RUN_NUMBERS} ; do
 				"id" "Proposal Users" "${new_user_list}" \
 				"old_user_list" "AllowMulti"
 			cklookup=$?
+			# NOTE: Sets Global ${ipts_old_line_wnum}...! ;-D
 
 			# Something Happened During Lookup...
 			if [[ ${cklookup} != 0 ]]; then
@@ -1578,7 +1656,7 @@ for run in ${RUN_NUMBERS} ; do
 
 	if [[ ${ckinstall} != 0 ]]; then
 		echo -e -n "\nERROR Installing and Checking "
-		echo -e "Modified Data File for Run ${run}!"
+		echo "Modified Data File for Run ${run}!"
 		echo -e "\nContinuing with Next Run Number..."
 		continue
 	fi
