A-Ha! Figured Out Proper Handling of Paused Data 	- in "ADARA Fix IPTS", when *Sending* Paused Data and using the 	"Last" Raw Data File, need to choose the "Last" of either the 	Paused _Or_ Non-Paused Data Files for editing... ;-D 		-> first look for the "Last" Non-Paused Data File 		-> then extract the "File Number" string 			=> NEW Naming Convention "m0001-f0001-"... 			=> OLD Naming Convention "f0001-"... 		-> now use the File Number string to search for an 		accompanying "Last" *Paused* Data File that "matches" 		the "Last" Non-Paused Data File found... ;-D 	- "un-did"/moved around my previous/partial fix, to apply it in a 	separate Paused Data File search, using the File Number string... 	- It Works...! :-D 		-> the only remaining as-yet-unresolved snafu left here now 		is the "Retry Index", which needs to be coordinated between 		the "Last" Non-Paused File and its "Nested" Paused Files... 			=> saving that very rare scenario for another day, 			in the hopes that it never comes up, lololol...! :-D

diff --git a/sms/adara_fix_ipts b/sms/adara_fix_ipts
--- a/sms/adara_fix_ipts
+++ b/sms/adara_fix_ipts
@@ -1895,24 +1895,45 @@ for run in ${RUN_NUMBERS} ; do
 					--regexp "^m[0-9]+-f[0-9]+-run-${run}.adara$" \
 					--regexp "^f[0-9]+-run-${run}.adara$" \
 				| ${HEAD} -${index} | ${TAIL} -1`
+			ckdatafile=$?
 		else # "${SMS_WHICH_DATA_FILE}" == "LAST"...
 			echo -e -n "\nLocating ${SMS_WHICH_DATA_FILE} Data File "
 			echo "for Run ${run}."
-			if [[ $SEND_PAUSED_DATA == "--send-paused-data" ]]; then
-				INCL_PAUSE_NEW="--regexp ^m[0-9]+-f[0-9]+-p[0-9]+-run-${run}.adara$"
-				INCL_PAUSE_OLD="--regexp ^f[0-9]+-p[0-9]+-run-${run}.adara$"
-			else
-				INCL_PAUSE_NEW=""
-				INCL_PAUSE_OLD=""
-			fi
 			datafile=`${LS} "${rundir}" \
 				| ${GREP} -E \
 					--regexp "^m[0-9]+-f[0-9]+-run-${run}.adara$" \
 					--regexp "^f[0-9]+-run-${run}.adara$" \
-					${INCL_PAUSE_NEW} ${INCL_PAUSE_OLD} \
 				| ${TAIL} -${index} | ${HEAD} -1`
+			ckdatafile=$?
+			# If Sending Paused Data (And We Found a Non-Paused Data File!)
+			# Then Look for (Last) Accompanying Paused Data File with the
+			# Same File Number as Our "Last" Data File...
+			# [TODO Note: This Screws Up the Use of the Retry Index...!]
+			if [[ ${ckdatafile} == 0 \
+					&& $SEND_PAUSED_DATA == "--send-paused-data" ]]; then
+				# Get "File Number" String from "Last" Data File...
+				# - New Raw Data File Naming Convention...
+				if [[ $datafile =~ ^m[0-9]+ ]]; then
+					fileNo=`echo "$datafile" | awk -F - '{print $1"-"$2}'`
+				# - Old Raw Data File Naming Convention...
+				else
+					fileNo=`echo "$datafile" | awk -F - '{print $1}'`
+				fi
+				pausedatafile=`${LS} "${rundir}" \
+					| ${GREP} -E \
+						--regexp "^${fileNo}-p[0-9]+-run-${run}.adara$" \
+					| ${TAIL} -${index} | ${HEAD} -1`
+				# If We Found One, Use _That_ In Place of Non-Paused Data
+				if [[ -n "${pausedatafile}" ]]; then
+					echo -e "\nSending Paused Data for This Run!"
+					echo -e "\nIn Place of Latest Non-Paused Data File:"
+					echo -e "   [${datafile}]"
+					echo -e "\nUsing Instead Oldest Paused Data File:"
+					echo -e "   [${pausedatafile}]"
+					datafile="${pausedatafile}"
+				fi
+			fi
 		fi
-		ckdatafile=$?
 
 		if [[ ${ckdatafile} != 0 ]]; then
 			echo -e -n "\nERROR Locating ${SMS_WHICH_DATA_FILE} "
