Implemented ABSORB_WHITE_SPACE() Method 	- in ADARA Fix IPTS Script... 		-> for generically searching the appropriate First/Last 		RunInfo XML specification in the First/Last Data File 		for "Unnecessary" White Space that can be Absorbed 		to Account for "Longer" New IPTS Meta-Data Values... 	- use "Preceding White Space" before XML Tags: 		-> <user>, </user> 		-> <users>, </users> 		-> <facility_name>, <instrument_name>, <run_number> 		-> <no_sample_info/> 		-> <name>, <role> 	- use LOOKUP_PROPOSAL_METADATA() to find Matching Lines in the 	"Right RunInfo Line Range"... 		-> process each candidate line in turn, "eroding" the 		Preceding White Space as Available... 			=> append Resulting Substitution to $SUBST_EXPRS. 	- Note: fixed funny formatting issue with "interrupted" loops 	with $SPACE_MARKER hash count output, wherein extra line breaks 	were being output... 		-> use dummy "$x" to conditionally use a "-n" for last line In Main Loop, Just Prior to Converting/Using Substitution Strings: 	- call ABSORB_WHITE_SPACE() as needed if $SPACES_NEEDED > 0... It Works! ;-D

diff --git a/sms/adara_fix_ipts b/sms/adara_fix_ipts
--- a/sms/adara_fix_ipts
+++ b/sms/adara_fix_ipts
@@ -1500,6 +1500,263 @@ UPDATE_PROPOSAL_METADATA()
 	return 0
 }
 
+ABSORB_WHITE_SPACE()
+{
+	echo -e -n "\nABSORB_WHITE_SPACE(): ${SPACES_NEEDED} Spaces "
+	echo "Still Needed for Meta-Data Changes."
+
+	# Potential XML Tag Targets for Extra White Space Absorption...
+	local _xml_tags="user /user users /users"
+	_xml_tags="${_xml_tags} facility_name instrument_name run_number"
+	_xml_tags="${_xml_tags} no_sample_info/ name role"
+
+	# Proceed Through XML Tag List Until Needed White Space Absorbed...
+
+	local _xml_tag=""
+
+	for _xml_tag in ${_xml_tags} ; do
+
+		if [[ ${SPACES_NEEDED} == 0 ]]; then
+
+			echo -e -n "\nABSORB_WHITE_SPACE(): "
+			echo "Resulting Substitution Strings are:"
+			echo -e "\n\t[${SUBST_EXPRS}]"
+
+			echo -e -n "\nAll Necessary White Space "
+			echo "has Been Absorbed!"
+
+			echo -e "\nWe're Done Absorbing White Space. Returning."
+
+			#
+			# (Optionally) Prompt to Continue...
+			#
+
+			if [[ $ERROR_ONLY_PROMPTING == 0 ]]; then
+				CHECK_PROCEED
+			fi
+
+			return
+
+		fi
+
+		aws_line_list_wnum=""
+
+		LOOKUP_PROPOSAL_METADATA \
+			"${_xml_tag}" "White Space Absorption" \
+			"SPACES_NEEDED=${SPACES_NEEDED}" \
+			"aws_line_list_wnum" "" "AllowMulti"
+		cklookup=$?
+
+		# Something Happened During Lookup...
+		if [[ ${cklookup} != 0 ]]; then
+
+			# [Not] Pass-Thru Return... (Already Manually Edited)
+			if [[ ${cklookup} != 255 ]]; then
+				echo -e -n "\nWARNING: Unable to Lookup "
+				echo "<${_xml_tag}> Meta-Data Tag Lines..."
+				echo -e "\nTry the Next Meta-Data XML Tag..."
+				continue
+			else
+
+				echo -e -n "\nABSORB_WHITE_SPACE(): "
+				echo "Resulting Substitution Strings are:"
+				echo -e "\n\t[${SUBST_EXPRS}]"
+
+				echo -e -n "\nGot Pass-Thru Return from "
+				echo "LOOKUP_PROPOSAL_METADATA()..."
+
+				echo -e "\nAssuming Manual Editing Completed. Return..."
+
+				SPACES_NEEDED=0
+
+				#
+				# (Optionally) Prompt to Continue...
+				#
+
+				if [[ $ERROR_ONLY_PROMPTING == 0 ]]; then
+					CHECK_PROCEED
+				fi
+
+				return
+
+			fi
+
+		# Lookup Succeeded, Go Thru Lines Absorbing Spaces...! ;-D
+		else
+
+			local _line_wnum=""
+
+			while IFS= read -r _line_wnum ; do
+
+				echo -e "\nGot <${_xml_tag}> Meta-Data Line:"
+				echo -e "\n\t[${_line_wnum}]"
+
+				# Separate Old Meta-Data Line into Line Number and Content
+
+				local _line_num=`echo "${_line_wnum}" \
+					| ${AWK} -F ":" '{print $1}'`
+				local _ckawklinenum=$?
+
+				if [[ ${_ckawklinenum} != 0 ]]; then
+					echo -e -n "\nERROR Extracting Line Number from "
+					echo "This Meta-Data Line...!"
+					echo -e "\nTry Next <${_xml_tag}> Meta-Data Line..."
+					continue
+				fi
+
+				local _line=`echo "${_line_wnum}" \
+					| ${AWK} -F ":" '{print $2}'`
+				local _ckawkline=$?
+
+				if [[ ${_ckawkline} != 0 ]]; then
+					echo -e -n "\nERROR Extracting Content from "
+					echo "This Meta-Data Line...!"
+					echo -e "\nTry Next <${_xml_tag}> Meta-Data Line..."
+					continue
+				fi
+
+				echo -e -n "\nExtracted Line Number and Content "
+				echo "from This <${_xml_tag}> Meta-Data Line:"
+				echo -e "\n${_line_wnum}\n"
+					# Allow Self-Indenting from XML Line(s)
+				echo -e "\t-> Line #${_line_num}"
+				echo -e "\t-> [${_line}]"
+					# Allow Self-Indenting from XML Line(s)
+
+				# Starting Point for Meta-Data Substitution Line...
+				local _new_line="${_line}"
+
+				# Try to Remove Sufficient Spaces from Meta-Data Line
+
+				echo -e "\nAbsorbing as Much White Space as Possible..."
+				echo
+
+				x=""
+
+				for (( i = 0 ; i < ${SPACES_NEEDED} ; ++i )); do
+
+					# *Only* Steal Spaces from _Before_ This Current Tag!
+					# I.e. Not from Subsequent Data Content...
+					ckspc=`echo "${_new_line}" \
+						| ${GREP} -c " <${_xml_tag}>"`
+					if [[ "${ckspc}" != "1" ]]; then   # Not 1 Line Found
+						if [[ ${i} -gt 0 ]]; then echo ; x="-n" ; fi
+						echo -e -n "\nDone with White Space Removal "
+						echo "in This <${_xml_tag}> Meta-Data Line."
+						echo -e -n "\n\tNeed ${SPACES_NEEDED} Spaces, "
+						echo ${x} "So Far Found $i..."
+						break
+					fi
+
+					# Take Any Space We Can Get (_Before_ This Tag)...! ;-D
+					_new_line=`echo "${_new_line}" \
+						| ${SED} "s@ <${_xml_tag}>@<${_xml_tag}>@"`
+							# Note: XML Tag Could Contain "/"
+							# for Embedded Tag!
+					cksedspc=$?
+
+					if [[ ${cksedspc} != 0 ]]; then
+						if [[ ${i} -gt 0 ]]; then echo ; x="-n" ; fi
+						echo -e -n "\nERROR Stripping White Space "
+						echo "from This <${_xml_tag}> Meta-Data Line...!"
+						echo -e ${x} "\nOnly Stripped Off $i Spaces..."
+						break
+					fi
+
+					echo -n "${SPACE_MARKER}"
+
+				done
+
+				if [[ ${i} -gt 0 ]]; then echo ; fi
+
+				SPACES_NEEDED=$(( ${SPACES_NEEDED} - ${i} ))
+				echo -e "\nSPACES_NEEDED -> [${SPACES_NEEDED}]..."
+
+				#
+				# Append Substitution to List
+				# (Using Specific Line Number from Selected Old
+				#    Meta-Data Line!)
+				#
+
+				echo -e -n "\nFinal <${_xml_tag}> Meta-Data "
+				echo "Line Substitution:"
+				echo -e "\tOld Line: [${_line}]"
+					# Allow Self-Indenting from XML Line(s)
+				echo -e "\tNew Line: [${_new_line}]"
+					# Allow Self-Indenting from XML Line(s)
+
+				subst="${_line_num}s@${_line}@${_new_line}@"
+
+				SUBST_EXPRS="$SUBST_EXPRS -e \"${subst}\""
+
+				if [[ ${SPACES_NEEDED} == 0 ]]; then
+					break
+				fi
+
+			done <<< "${aws_line_list_wnum}"
+
+			echo -e "\nWe're Done with This <${_xml_tag}> Meta-Data Tag."
+
+			echo -e -n "\nABSORB_WHITE_SPACE(): "
+			echo "Resulting Substitution Strings are:"
+			echo -e "\n\t[${SUBST_EXPRS}]"
+
+			if [[ ${SPACES_NEEDED} == 0 ]]; then
+
+				echo -e -n "\nAll Necessary White Space "
+				echo "has Been Absorbed!"
+
+				#
+				# (Optionally) Prompt to Continue...
+				#
+
+				if [[ $ERROR_ONLY_PROMPTING == 0 ]]; then
+					CHECK_PROCEED
+				fi
+
+				return
+
+			else
+
+				#
+				# (Optionally) Prompt to Continue...
+				#
+
+				if [[ $ERROR_ONLY_PROMPTING == 0 ]]; then
+					CHECK_PROCEED
+				fi
+
+			fi
+
+		fi
+
+	done
+
+	# Done Here...
+
+	if [[ ${SPACES_NEEDED} -gt 0 ]]; then
+
+		echo -e "\nABSORB_WHITE_SPACE() All Meta-Data Tags Exhausted..."
+		echo -e -n "\n${SPACES_NEEDED} Spaces are *Still* Needed "
+		echo "for Meta-Data Changes!"
+		echo -e "\nDeferring to Manual Editing After Substitutions..."
+
+	else
+
+		echo -e "\nAll Necessary White Space has Been Absorbed!"
+		echo -e "\nWe're Done Absorbing White Space. Returning."
+
+	fi
+
+	#
+	# (Optionally) Prompt to Continue...
+	#
+
+	if [[ $ERROR_ONLY_PROMPTING == 0 ]]; then
+		CHECK_PROCEED
+	fi
+}
+
 #
 # Process Each Run Number in Turn...
 #
@@ -1963,17 +2220,19 @@ for run in ${RUN_NUMBERS} ; do
 
 		echo
 
+		x=""
+
 		for (( i = 0 ; i < ${num_spaces} ; ++i )); do
 
 			# Make Sure There are Still Some Spaces Left...
 			ckspc=`echo "${SUBST_EXPRS}" \
 				| ${GREP} -o "${SPACE_MARKER}" | wc | awk '{print $1}'`
 			if [[ ${ckspc} -lt 1 ]]; then   # No Space Markers Found...
-				if [[ ${i} -gt 0 ]]; then echo ; fi
+				if [[ ${i} -gt 0 ]]; then echo ; x="-n" ; fi
 				echo -e -n "\nERROR: Insufficient White Space Markers "
 				echo "to Absorb in Substitution Strings!"
 				echo -e -n "\n\tExpected ${num_spaces} Markers "
-				echo "But Only Found $i..."
+				echo ${x} "But Only Found $i..."
 				break
 			fi
 
@@ -1983,12 +2242,10 @@ for run in ${RUN_NUMBERS} ; do
 			cksedmrk=$?
 
 			if [[ ${cksedmrk} != 0 ]]; then
-				if [[ ${i} -gt 0 ]]; then echo ; fi
+				if [[ ${i} -gt 0 ]]; then echo ; x="-n" ; fi
 				echo -e -n "\nERROR Abosrbing White Space Markers "
 				echo "from Substitution Strings!"
-				echo -e "\nOnly Absorbed $i Markers..."
-				SPACES_NEEDED=$(( ${SPACES_NEEDED} - ${i} ))
-				echo -e "\nSPACES_NEEDED Remaining -> [${SPACES_NEEDED}]"
+				echo -e ${x} "\nOnly Absorbed $i Markers..."
 				break
 			fi
 
@@ -2004,10 +2261,24 @@ for run in ${RUN_NUMBERS} ; do
 		echo -e "\nResulting Substitution Strings are:"
 		echo -e "\n\t[${SUBST_EXPRS}]"
 
+		#
+		# (Optionally) Prompt to Continue...
+		#
+
 		if [[ $ERROR_ONLY_PROMPTING == 0 ]]; then
 			CHECK_PROCEED
 		fi
 
+	fi
+
+	#
+	# Still Need Yet More White Space Absorbed in Meta-Data...!
+	# Last Ditch Before Deferring to Manual Editing (_After_ # Substitute!)
+	# Try to Find More Absorbable White Space in RunInfo Meta-Data...
+	#
+
+	if [[ ${SPACES_NEEDED} -gt 0 ]]; then
+		ABSORB_WHITE_SPACE
 	fi
 
 	#
