Add All-Important SMS Data Disk Full Check!! 	- Kaz and Bogdan could have used this in advance of last night's 	nightmare on HB2C, where an SMS MaxBlocksAllowed Bug allowed 	the 5.0TB /SNSlocal/ disk to fill up...! ;-b 	- add an "Every Time" Disk Full Check (every 10 minutes cron job) 		-> define SMS_DATA directory "${SMS_HOME}/${SMS}/data/" 		-> check "df -h" and snag percent used ($(NF-1)) 		-> if percent used >= 85%, then Log as Error 			=> use CHECK_ERROR_REPORTING to set $do_report 			=> spew the "Data Filesystem Getting Full" error 			with the latest percentage full 			=> set a "disk_full" error message for the Log file 	- for now, keep ye olde "Log File Filesystem" Percent/Full Check 		-> this must have bitten us for hysterical reasons long ago, 		perhaps before SMSD had proper log rotation...?! ;-} 		-> adjust to 8am and 5pm like everything else nowadays... 		-> remove the extra/premature SET_ERROR_COUNT & exit clauses 			=> let's keep this all on the same page... ;-) 	- move the actual scribbling to the Log File to the Very End...! 		-> So We Don't Corrupt Any Error Count at the 		Tail of the Log file...! ;-D 	- It Works! ;-D 		-> for now, deploying to /SNS/users/y8y/stuff/exec/smsd_mon 		so everyone can use it immediately 			=> need to merge changes into VENUS/DAS 3.0 setup!

diff --git a/sms/smsd_mon b/sms/smsd_mon
--- a/sms/smsd_mon
+++ b/sms/smsd_mon
@@ -446,28 +446,54 @@ cpuT=`echo "$status" | awk '{print $10}'`
 log="$log time=$cpuT"
 
 #
-# Dump SMS Daemon Status Snapshot into Log file...
+# Check on the SMS Local Data Filesystem Usage...
+#
+# (Eminently More Important than checking the Log File Size, lol... ;-D)
 #
 
-if [[ -w "${LOGFILE}" ]]; then
+SMS_DATA="${SMS_HOME}/${SMS}/data/"
 
-	echo -e "$log" >> ${LOGFILE}
+data_usage=`df -h ${SMS_DATA}`
+#echo -e "data_usage:\n${data_usage}"
 
-# Only Whine Once Per Hour If We've Become Disconnected from the Universe...
-elif [[ $min -eq ${SOS_MIN} ]]; then
+data_pct_str=`echo -e "${data_usage}" | tail -1 | awk '{print $(NF-1)}'`
+#echo "data_pct_str=[$data_pct_str]"
 
-	echo -e "${NL}Error: SMS Daemon Monitor Log File Unwritable!"
-	echo -e "\n$log"
-	NL="\n"
+data_pct="${data_pct_str%"%"}"
+#echo "data_pct=[$data_pct]"
+
+# Nominally, We Usually Shoot for 80% Full at Most...
+# -> Check for 85%, to Give Some Head Room for "Other Stuff"
+#    that may Also be Stored Under /SNSlocal/...
+
+if [[ ${data_pct} -ge 85 ]]; then
+
+	# Error for Log file... (Don't Write Now, Else Breaks Error Count!)
+	disk_full="*** Data Filesystem Getting Full at ${data_pct}%!!"
+
+	CHECK_ERROR_REPORTING
+	do_report="$?"
+
+	# Report Error...
+	if [[ $do_report == 1 ]]; then
+
+		echo -e -n "${NL}Error on ${host}: Data Filesystem Getting Full"
+		echo -e " at ${data_pct}% for SMS${ALTLABEL}!\n"
+		echo -e "${data_usage}"
+		NL="\n"
+
+	fi
 
 fi
 
 #
 # Check on the SMS Daemon Log File size/usage...
 #
+# (Done for Hysterical Reasons, Probably Before Log Rotation, Lol... ;-D)
+#
 
-# Only check once or twice per day maybe...?
-if [[ ( $hour -eq 10 || $hour -eq 16 ) && $min -eq 0 ]]; then
+# Check Twice Per Day, 8am and 5pm...
+if [[ ( $hour -eq 8 || $hour -eq 17 ) && $min -eq 0 ]]; then
 
 	log_bytes=`/bin/ls -l $SMSD_LOG | awk '{print $5}'`
 	log_hbytes=`/bin/ls -lh $SMSD_LOG | awk '{print $5}'`
@@ -534,14 +560,6 @@ if [[ ( $hour -eq 10 || $hour -eq 16 ) && $min -eq 0 ]]; then
 	#		echo "   $SMSD_LOG $log_bytes ($log_hbytes)"
 	#		NL="\n"
 	#	fi
-	#	# Set Error Count for Next Invocation,
-	#	if [[ ${ERROR_COUNT} -gt 0 ]]; then
-	#		SET_ERROR_COUNT
-	#		if [[ ${log_error} != 0 ]]; then
-	#			echo -e "${NL}ErrorCount=${ERROR_COUNT}"
-	#		fi
-	#	fi
-	#	exit -2
 	# fi
 
 	if [[ $pct_used -gt 80 ]]; then
@@ -557,17 +575,35 @@ if [[ ( $hour -eq 10 || $hour -eq 16 ) && $min -eq 0 ]]; then
 			NL="\n"
 		fi
 
-		# Set Error Count for Next Invocation,
-		if [[ ${ERROR_COUNT} -gt 0 ]]; then
-			SET_ERROR_COUNT
-			if [[ ${log_error} != 0 ]]; then
-				echo -e "${NL}ErrorCount=${ERROR_COUNT}"
-			fi
-		fi
-
-		exit -3
-
 	fi
+
+fi
+
+#
+# Dump SMS Daemon Status Snapshot into Log file...
+#
+# (Do This at the Very End, So We Don't Corrupt Any Error Count
+#    at the Tail of the Log file...! ;-D)
+#
+
+if [[ -w "${LOGFILE}" ]]; then
+
+	echo -e "$log" >> ${LOGFILE}
+
+	if [[ -n "${data_usage}" ]]; then
+		echo -e "${data_usage}" >> ${LOGFILE}
+	fi
+
+	if [[ -n "${disk_full}" ]]; then
+		echo -e "${disk_full}" >> ${LOGFILE}
+	fi
+
+# Only Whine Once Per Hour If We've Become Disconnected from the Universe...
+elif [[ $min -eq ${SOS_MIN} ]]; then
+
+	echo -e "${NL}Error: SMS Daemon Monitor Log File Unwritable!"
+	echo -e "\n$log"
+	NL="\n"
 
 fi
 
@@ -582,6 +618,6 @@ if [[ ${ERROR_COUNT} -gt 0 ]]; then
 	if [[ ${log_error} != 0 ]]; then
 		echo -e "${NL}ErrorCount=${ERROR_COUNT}"
 	fi
-	exit -4
+	exit -2
 fi
 
