Exponential Fall Off Error Reporting - SMS Monitor 	- capture error states from invocation to invocation using log file 		-> capture errors and scribble/append to log file: 			=> "ErrorCount=N", where "N" is accumulated count 		-> when errors occur, check saved Error Count state and 		apply exponential fall off error reporting... 			=> log first 3 errors normally, then Once per Hour 			=> after first 3 hours, then Once per Day 			=> after first 3 days, then Once per Week 	- new functions to implement error reporting state capture: 		-> $ERROR_COUNT global, initialized to 0 		-> GET_ERROR_COUNT() 			=> read last line of Log File, look for ErrorCount=N 			=> Error Count incremented to 1 on new error state 		-> SET_ERROR_COUNT() 			=> scribble/append latest accumulated Error Count 			to end of Log File (*After All Other Log Output*!) 		-> CHECK_ERROR_REPORTING() 			=> using GET_ERROR_COUNT() update latest Error Count 			=> decide if this invocation should Report Errors 	- move creation of Log Sub-Directory and Log File to script start 	- apply CHECK_ERROR_REPORTING() everywhere Error Logging would occur 		-> SMS Daemon Not Running as User... 		-> Channel Connect Timed Out on Summary PV... 		-> Timed Out 3 Times on SMS Summary Status PV... 		-> Summary Status Not OK! 		-> SMS Config File Not Found (for Summary Status PV Prefix) 		-> SMS Log Directory 80% Full 	- always call SET_ERROR_COUNT() prior to exit() if Error Count Set!

diff --git a/sms/smsd_mon b/sms/smsd_mon
--- a/sms/smsd_mon
+++ b/sms/smsd_mon
@@ -98,6 +98,104 @@ min=`echo $date | awk '{print $4}' | awk -F ":" '{print $2}' \
 	| sed 's/^0//g'`
 #echo "min=$min"
 
+# If Log Sub-Directory Doesn't Exist, Try to Create It... ;-D
+if [[ ! -d "${LOG_HOME}/${LOG_DIR}" ]]; then
+
+	ckd=`mkdir -p "${LOG_HOME}/${LOG_DIR}" 2>&1`
+
+	# Only Whine Once Per Hour If There's No Log Sub-Directory
+	# (And We Can't Create It...)
+	if [[ $? != 0 && $min -eq ${SOS_MIN} ]]; then
+		echo -e "${NL}Error Creating SMS Daemon Monitor Log Sub-Directory!"
+		echo -e "\n${ckd}"
+		NL="\n"
+	fi
+
+fi
+
+# If Log File Doesn't Exist, Try to Create It... ;-D
+if [[ ! -e "${LOGFILE}" ]]; then
+
+	ckt=`touch "${LOGFILE}" 2>&1`
+
+	# Only Whine Once Per Hour If There's No Log File
+	# (And We Can't Create It...)
+	if [[ $? != 0 && $min -eq ${SOS_MIN} ]]; then
+		echo -e "${NL}Error Creating SMS Daemon Monitor Log File!"
+		echo -e "\n${ckt}"
+		NL="\n"
+	fi
+
+fi
+
+# Track Any Error Count Already Retrieved for This Invocation...
+ERROR_COUNT=0
+
+# Check Error Count Embedded in Last Line of Log File...
+GET_ERROR_COUNT()
+{
+	# Only Retrieve Error Count from Log File If Not Already Set...!
+	if [[ $ERROR_COUNT == 0 ]]; then
+		if [[ -r "${LOGFILE}" ]]; then
+			local _last=`tail -1 "${LOGFILE}"`
+			if [[ "${_last}" =~ ErrorCount= ]]; then
+				ERROR_COUNT=`echo "${_last}" | awk -F "=" '{print $2}'`
+			fi
+		fi
+		# Add 1 for This Invocation's New Error...
+		ERROR_COUNT=$(( ERROR_COUNT + 1 ))
+	fi
+}
+
+# Set Error Count, Append as Last Line of Log File...
+SET_ERROR_COUNT()
+{
+	if [[ -w "${LOGFILE}" ]]; then
+
+		echo "ErrorCount=${ERROR_COUNT}" >> ${LOGFILE}
+
+	# Only Whine Once Per Hour If We've Become
+	# Disconnected from the Universe...
+	elif [[ $min -eq ${SOS_MIN} ]]; then
+		echo -e -n "${NL}Error Writing Error Count (${ERROR_COUNT})"
+		echo " to SMS Daemon Monitor Log File!"
+		echo -e "\n${ckt}"
+		NL="\n"
+	fi
+}
+
+# We've Just Encountered an Error...!
+# Implement Exponential Error Reporting Fall Off...
+# (Based on Cron Job Check Every 10 Minutes)
+CHECK_ERROR_REPORTING()
+{
+	local _do_report=1
+
+	# Check for Any Saved "Error Count" from Last Invocation...
+	GET_ERROR_COUNT
+
+	# After First 3 Days, Report Once Per Week...
+	if [[ ${ERROR_COUNT} -gt 433 ]]; then
+		if [[ $(( ( ERROR_COUNT - 1 ) % 1008 )) != 0 ]]; then
+			_do_report=0
+		fi
+
+	# After First 3 Hours, Report Once Per Day...
+	elif [[ ${ERROR_COUNT} -gt 19 ]]; then
+		if [[ $(( ( ERROR_COUNT - 1 ) % 144 )) != 0 ]]; then
+			_do_report=0
+		fi
+
+	# Report First 3 Occurrences in a Row, Then Once Per Hour...
+	elif [[ ${ERROR_COUNT} -gt 3 ]]; then
+		if [[ $(( ( ERROR_COUNT - 1 ) % 6 )) != 0 ]]; then
+			_do_report=0
+		fi
+	fi
+
+	return ${_do_report}
+}
+
 #
 # Get SMS Daemon process status...
 #
@@ -108,9 +206,27 @@ status=`ps augxww | grep $SMSD | grep -v -e $PROG -e $TIME -e grep | grep $SMSD_
 if [ "#$status#" == '##' ]; then
 
 	if [ $do_notify == 1 ]; then
-		echo -n "Error on ${host}:"
-		echo " SMS${ALTLABEL} Daemon $SMSD Not Running as User $SMSD_USER!"
+
+		CHECK_ERROR_REPORTING
+		do_report="$?"
+
+		# Report Error...
+		if [[ $do_report == 1 ]]; then
+
+			echo -e -n "${NL}Error on ${host}:"
+			echo \
+			" SMS${ALTLABEL} Daemon $SMSD Not Running as User $SMSD_USER!"
+			NL="\n"
+
+		fi
+
+		# Set Error Count for Next Invocation,
+		if [[ ${ERROR_COUNT} -gt 0 ]]; then
+			SET_ERROR_COUNT
+		fi
+
 		exit -1
+
 	else
 		# Just Exit Cleanly, Nothing to log here... ;-D
 		exit 0
@@ -146,8 +262,18 @@ if [ $do_notify == 1 ]; then
 
 			# Did We Time Out Connecting to the SMS Summary PV...?
 			if [[ "$summary" =~ Channel${S}connect${S}timed${S}out ]]; then
-				echo "Channel Connect Timed Out on: ${summaryPV}..."
-				cnt=$(( $cnt + 1 ))
+
+				CHECK_ERROR_REPORTING
+				do_report="$?"
+
+				# Report Error...
+				if [[ $do_report == 1 ]]; then
+					echo -e \
+						"${NL}Channel Connect Timed Out on: ${summaryPV}..."
+					cnt=$(( $cnt + 1 ))
+					NL="\n"
+				fi
+
 			else
 				break
 			fi
@@ -156,14 +282,23 @@ if [ $do_notify == 1 ]; then
 
 		if [[ "$summary" =~ Channel${S}connect${S}timed${S}out ]]; then
 
-			echo -e -n "Error on ${host}: Timed Out $cnt Times"
-			echo -e " on SMS${ALTLABEL} Summary Status PV!\n"
-			echo -e "   ${summary}\n"
+			CHECK_ERROR_REPORTING
+			do_report="$?"
 
-			caget ${WAIT} -a "${prefix}:SMS:Recording"
-			caget ${WAIT} "${prefix}:SMS:RunNumber"
-			caget ${WAIT} "${summaryPV}"
-			caget ${WAIT} -S "${prefix}:SMS:SummaryReason"
+			# Report Error...
+			if [[ $do_report == 1 ]]; then
+
+				echo -e -n "${NL}Error on ${host}: Timed Out $cnt Times"
+				echo -e " on SMS${ALTLABEL} Summary Status PV!\n"
+				echo -e "   ${summary}\n"
+				NL="\n"
+
+				caget ${WAIT} -a "${prefix}:SMS:Recording"
+				caget ${WAIT} "${prefix}:SMS:RunNumber"
+				caget ${WAIT} "${summaryPV}"
+				caget ${WAIT} -S "${prefix}:SMS:SummaryReason"
+
+			fi
 
 		else
 
@@ -173,13 +308,22 @@ if [ $do_notify == 1 ]; then
 
 			if [[ "${summary}" != "OK" ]]; then
 
-				echo -e -n "Error on ${host}:"
-				echo -e " SMS${ALTLABEL} Summary Status Not OK!\n"
+				CHECK_ERROR_REPORTING
+				do_report="$?"
 
-				caget ${WAIT} -a "${prefix}:SMS:Recording"
-				caget ${WAIT} "${prefix}:SMS:RunNumber"
-				caget ${WAIT} "${summaryPV}"
-				caget ${WAIT} -S "${prefix}:SMS:SummaryReason"
+				# Report Error...
+				if [[ $do_report == 1 ]]; then
+
+					echo -e -n "${NL}Error on ${host}:"
+					echo -e " SMS${ALTLABEL} Summary Status Not OK!\n"
+					NL="\n"
+
+					caget ${WAIT} -a "${prefix}:SMS:Recording"
+					caget ${WAIT} "${prefix}:SMS:RunNumber"
+					caget ${WAIT} "${summaryPV}"
+					caget ${WAIT} -S "${prefix}:SMS:SummaryReason"
+
+				fi
 
 			fi
 
@@ -187,10 +331,17 @@ if [ $do_notify == 1 ]; then
 
 	else
 
-		echo -n "Error on ${host}:"
-		echo " SMS${ALTLABEL} ${SMSD}${ALT} Config File Not Found!"
-		echo -e "\n\t[${SMSD_CONFIG}]\n"
-		/bin/ls -l ${SMSD_CONFIG}
+		CHECK_ERROR_REPORTING
+		do_report="$?"
+
+		# Report Error...
+		if [[ $do_report == 1 ]]; then
+			echo -e -n "${NL}Error on ${host}:"
+			echo " SMS${ALTLABEL} ${SMSD}${ALT} Config File Not Found!"
+			echo -e "\n\t[${SMSD_CONFIG}]\n"
+			/bin/ls -l ${SMSD_CONFIG}
+			NL="\n"
+		fi
 
 	fi
 
@@ -233,36 +384,6 @@ log="$log time=$cpuT"
 #
 # Dump SMS Daemon Status Snapshot into Log file...
 #
-
-# If Log Sub-Directory Doesn't Exist, Try to Create It... ;-D
-if [[ ! -d "${LOG_HOME}/${LOG_DIR}" ]]; then
-
-	ckd=`mkdir -p "${LOG_HOME}/${LOG_DIR}" 2>&1`
-
-	# Only Whine Once Per Hour If There's No Log Sub-Directory
-	# (And We Can't Create It...)
-	if [[ $? != 0 && $min -eq ${SOS_MIN} ]]; then
-		echo -e "${NL}Error Creating SMS Daemon Monitor Log Sub-Directory!"
-		echo -e "\n${ckd}"
-		NL="\n"
-	fi
-
-fi
-
-# If Log File Doesn't Exist, Try to Create It... ;-D
-if [[ ! -e "${LOGFILE}" ]]; then
-
-	ckt=`touch "${LOGFILE}" 2>&1`
-
-	# Only Whine Once Per Hour If There's No Log File
-	# (And We Can't Create It...)
-	if [[ $? != 0 && $min -eq ${SOS_MIN} ]]; then
-		echo -e "${NL}Error Creating SMS Daemon Monitor Log File!"
-		echo -e "\n${ckt}"
-		NL="\n"
-	fi
-
-fi
 
 if [[ -w "${LOGFILE}" ]]; then
 
@@ -340,16 +461,49 @@ if [[ ( $hour -eq 10 || $hour -eq 16 ) && $min -eq 0 ]]; then
 
 	# Seemed like a good idea at the time... ;-D
 	# if [[ $pct_log -gt 80 ]]; then
-	# 	echo -n "Error on ${host}:"
-	#	echo " SMS${ALTLABEL} Daemon Log is $pct_log% of Usage!"
-	# 	echo "   $SMSD_LOG $log_bytes ($log_hbytes)"
-	# 	exit -2
+	#	CHECK_ERROR_REPORTING
+	#	do_report="$?"
+	#	# Report Error...
+	#	if [[ $do_report == 1 ]]; then
+	#		echo -e -n "${NL}Error on ${host}:"
+	#		echo " SMS${ALTLABEL} Daemon Log is $pct_log% of Usage!"
+	#		echo "   $SMSD_LOG $log_bytes ($log_hbytes)"
+	#		NL="\n"
+	#	fi
+	#	# Set Error Count for Next Invocation,
+	#	if [[ ${ERROR_COUNT} -gt 0 ]]; then
+	#		SET_ERROR_COUNT
+	#	fi
+	#	exit -2
 	# fi
 
 	if [[ $pct_used -gt 80 ]]; then
-		echo "Error on ${host}: $smsd_top_logdir is $pct_used% Full!"
-		echo "   $SMSD_LOG $log_bytes ($log_hbytes)"
+
+		CHECK_ERROR_REPORTING
+		do_report="$?"
+
+		# Report Error...
+		if [[ $do_report == 1 ]]; then
+			echo -e -n "${NL}Error on ${host}:"
+			echo " $smsd_top_logdir is $pct_used% Full!"
+			echo "   $SMSD_LOG $log_bytes ($log_hbytes)"
+			NL="\n"
+		fi
+
+		# Set Error Count for Next Invocation,
+		if [[ ${ERROR_COUNT} -gt 0 ]]; then
+			SET_ERROR_COUNT
+		fi
+
 		exit -3
+
 	fi
+
+fi
+
+# Set Error Count for Next Invocation,
+if [[ ${ERROR_COUNT} -gt 0 ]]; then
+	SET_ERROR_COUNT
+	exit -4
 fi
 
