Add Deployment of ADARA Data Find Script! :-D 	- sms/adara_data_find

diff --git a/deploy_adara b/deploy_adara
--- a/deploy_adara
+++ b/deploy_adara
@@ -830,6 +830,30 @@ if [ $need_build == 1 ]; then
 
 	fi
 
+	# SMS ADARA Data Find Script (if present, added in v1.6.26...)
+
+	if [[ -e sms/adara_data_find && -x sms/adara_data_find ]]; then
+
+		echo -e -n "\nCopying SMS ADARA Data Find Script " | tee -a $LOG
+		echo -e "into Archive Release Tag:\n" | tee -a $LOG
+
+		cp -i -p sms/adara_data_find "$tag_archive" |& tee -a $LOG
+
+		copy_ok=$?
+
+		if [ $copy_ok != 0 ]; then
+			echo -e -n "\nError Copying ADARA Data Find Script " \
+				| tee -a $LOG
+			echo -e "into Release Tag Directory! ($copy_ok)\n" \
+				| tee -a $LOG
+			echo "Bailing Out..." | tee -a $LOG
+			exit -21
+		fi
+
+		/bin/ls -l "$tag_archive/adara_data_find" |& tee -a $LOG
+
+	fi
+
 	# STS Client
 
 	echo -e "\nCopying STS Client Executable into Archive Release Tag:\n" \
