Exponential Fall Off Error Reporting for DASMON... 	- applied latest cron job monitor script improvements from SMS...! 	- capture error states from invocation to invocation using log file 		-> capture errors and scribble/append to log file: 			=> "ErrorCount=N", where "N" is accumulated count 		-> when errors occur, check saved Error Count state and 		apply exponential fall off error reporting... 			=> log first 3 errors normally, then Once per Hour 			=> after first 3 hours, then Once per Day 			=> after first 3 days, then Once per Week 	- new functions to implement error reporting state capture: 		-> $ERROR_COUNT global, initialized to 0 		-> GET_ERROR_COUNT() 			=> read last line of Log File, look for ErrorCount=N 			=> Error Count incremented to 1 on new error state 		-> SET_ERROR_COUNT() 			=> scribble/append latest accumulated Error Count 		to end of Log File (*After All Other Log Output*!) 		-> CHECK_ERROR_REPORTING() 			=> using GET_ERROR_COUNT() update latest Error Count 			=> decide if this invocation should Report Errors 	- move creation of Log Sub-Directory and Log File to script start 	- apply CHECK_ERROR_REPORTING() everywhere Error Logging would occur 		-> DASMOND Not Running as User... 		-> DASMOND Log Directory 80% Full 	- always call SET_ERROR_COUNT() prior to exit() if Error Count Set!

diff --git a/dasmon/server/dasmond_mon b/dasmon/server/dasmond_mon
--- a/dasmon/server/dasmond_mon
+++ b/dasmon/server/dasmond_mon
@@ -16,17 +16,17 @@ host=`hostname`
 host_short=`echo $host | awk -F '.' '{print $1}'`
 #echo "host_short=$host_short"
 
-LOG_DIR="dasmond_mon"
+PROG="dasmond_mon"
 
-LOGFILE="${LOG_HOME}/${LOG_DIR}/dasmond_mon.$host_short.log"
-LOGLOGFILE="${LOG_HOME}/${LOG_DIR}/dasmond_mon.$host_short-log.log"
+LOG_DIR="${PROG}"
+
+LOGFILE="${LOG_HOME}/${LOG_DIR}/${PROG}.$host_short.log"
+LOGLOGFILE="${LOG_HOME}/${LOG_DIR}/${PROG}.$host_short-log.log"
 
 DASMOND_USER="dasmon"
 DASMOND="/usr/sbin/dasmond"
 
 DASMOND_LOG="/var/log/dasmond.log"
-
-PROG="dasmond_mon"
 
 TIME="/usr/bin/time" # for Test Harness, duh... ;-b
 
@@ -51,7 +51,7 @@ for arg in "$@" ; do
 	elif [ "#$key#" == '#--dasmond_user#' ]; then
 		DASMOND_USER="$value"
 	elif [ "#$key#" == '#--help#' ]; then
-		echo "usage:  dasmond_mon [--no_notify] [--dasmond_user=y8y]"
+		echo "usage:  ${PROG} [--no_notify] [--dasmond_user=y8y]"
 		exit 0
 	fi
 
@@ -69,6 +69,104 @@ min=`echo $date | awk '{print $4}' | awk -F ":" '{print $2}' \
 	| sed 's/^0//g'`
 #echo "min=$min"
 
+# If Log Sub-Directory Doesn't Exist, Try to Create It... ;-D
+if [[ ! -d "${LOG_HOME}/${LOG_DIR}" ]]; then
+
+	ckd=`mkdir -p "${LOG_HOME}/${LOG_DIR}" 2>&1`
+
+	# Only Whine Once Per Hour If There's No Log Sub-Directory
+	# (And We Can't Create It...)
+	if [[ $? != 0 && $min -eq ${SOS_MIN} ]]; then
+		echo -e "${NL}Error Creating DASMON Monitor Log Sub-Directory!"
+		echo -e "\n${ckd}"
+		NL="\n"
+	fi
+
+fi
+
+# If Log File Doesn't Exist, Try to Create It... ;-D
+if [[ ! -e "${LOGFILE}" ]]; then
+
+	ckt=`touch "${LOGFILE}" 2>&1`
+
+	# Only Whine Once Per Hour If There's No Log File
+	# (And We Can't Create It...)
+	if [[ $? != 0 && $min -eq ${SOS_MIN} ]]; then
+		echo -e "${NL}Error Creating DASMON Monitor Log File!"
+		echo -e "\n${ckt}"
+		NL="\n"
+	fi
+
+fi
+
+# Track Any Error Count Already Retrieved for This Invocation...
+ERROR_COUNT=0
+
+# Check Error Count Embedded in Last Line of Log File...
+GET_ERROR_COUNT()
+{
+	# Only Retrieve Error Count from Log File If Not Already Set...!
+	if [[ $ERROR_COUNT == 0 ]]; then
+		if [[ -r "${LOGFILE}" ]]; then
+			local _last=`tail -1 "${LOGFILE}"`
+			if [[ "${_last}" =~ ErrorCount= ]]; then
+				ERROR_COUNT=`echo "${_last}" | awk -F "=" '{print $2}'`
+			fi
+		fi
+		# Add 1 for This Invocation's New Error...
+		ERROR_COUNT=$(( ERROR_COUNT + 1 ))
+	fi
+}
+
+# Set Error Count, Append as Last Line of Log File...
+SET_ERROR_COUNT()
+{
+	if [[ -w "${LOGFILE}" ]]; then
+
+		echo "ErrorCount=${ERROR_COUNT}" >> ${LOGFILE}
+
+	# Only Whine Once Per Hour If We've Become
+	# Disconnected from the Universe...
+	elif [[ $min -eq ${SOS_MIN} ]]; then
+		echo -e -n "${NL}Error Writing Error Count (${ERROR_COUNT})"
+		echo " to DASMON Monitor Log File!"
+		echo -e "\n${ckt}"
+		NL="\n"
+	fi
+}
+
+# We've Just Encountered an Error...!
+# Implement Exponential Error Reporting Fall Off...
+# (Based on Cron Job Check Every 10 Minutes)
+CHECK_ERROR_REPORTING()
+{
+	local _do_report=1
+
+	# Check for Any Saved "Error Count" from Last Invocation...
+	GET_ERROR_COUNT
+
+	# After First 3 Days, Report Once Per Week...
+	if [[ ${ERROR_COUNT} -gt 433 ]]; then
+		if [[ $(( ( ERROR_COUNT - 1 ) % 1008 )) != 0 ]]; then
+			_do_report=0
+		fi
+
+	# After First 3 Hours, Report Once Per Day...
+	elif [[ ${ERROR_COUNT} -gt 19 ]]; then
+		if [[ $(( ( ERROR_COUNT - 1 ) % 144 )) != 0 ]]; then
+			_do_report=0
+		fi
+
+	# Report First 3 Occurrences in a Row, Then Once Per Hour...
+	elif [[ ${ERROR_COUNT} -gt 3 ]]; then
+		if [[ $(( ( ERROR_COUNT - 1 ) % 6 )) != 0 ]]; then
+			_do_report=0
+		fi
+	fi
+
+	return ${_do_report}
+}
+
 #
 # Get DASMOND process status...
 #
@@ -80,16 +178,35 @@ status=`ps augxww | grep $DASMOND | grep -v -e $PROG -e $TIME -e grep \
 if [ "#$status#" == '##' ]; then
 
 	if [ $do_notify == 1 ]; then
-		echo -n "Error on ${host}: DASMOND $DASMOND"
-		echo " Not Running as User $DASMOND_USER!"
+
+		CHECK_ERROR_REPORTING
+		do_report="$?"
+
+		# Report Error...
+		if [[ $do_report == 1 ]]; then
+
+			echo -e -n "${NL}Error on ${host}:"
+			echo " DASMOND $DASMOND Not Running as User $DASMOND_USER!"
+			NL="\n"
+
+		fi
+
+		# Set Error Count for Next Invocation,
+		if [[ ${ERROR_COUNT} -gt 0 ]]; then
+			SET_ERROR_COUNT
+		fi
+
 		exit -1
+
 	else
 		# Just Exit Cleanly, Nothing to log here... ;-D
 		exit 0
 	fi
 fi
 
-# Extract statistics of interest
+#
+# Extract & log statistics of interest
+#
 
 log="$date $host $DASMOND as ${DASMOND_USER}:\n  "
 
@@ -124,36 +241,6 @@ log="$log time=$cpuT"
 #
 # Dump DASMOND Status Snapshot into Log file...
 #
-
-# If Log Sub-Directory Doesn't Exist, Try to Create It... ;-D
-if [[ ! -d "${LOG_HOME}/${LOG_DIR}" ]]; then
-
-	ckd=`mkdir -p "${LOG_HOME}/${LOG_DIR}" 2>&1`
-
-	# Only Whine Once Per Hour If There's No Log Sub-Directory
-	# (And We Can't Create It...)
-	if [[ $? != 0 && $min -eq ${SOS_MIN} ]]; then
-		echo -e "${NL}Error Creating DASMON Monitor Log Sub-Directory!"
-		echo -e "\n${ckd}"
-		NL="\n"
-	fi
-
-fi
-
-# If Log File Doesn't Exist, Try to Create It... ;-D
-if [[ ! -e "${LOGFILE}" ]]; then
-
-	ckt=`touch "${LOGFILE}" 2>&1`
-
-	# Only Whine Once Per Hour If There's No Log File
-	# (And We Can't Create It...)
-	if [[ $? != 0 && $min -eq ${SOS_MIN} ]]; then
-		echo -e "${NL}Error Creating DASMON Monitor Log File!"
-		echo -e "\n${ckt}"
-		NL="\n"
-	fi
-
-fi
 
 if [[ -w "${LOGFILE}" ]]; then
 
@@ -231,15 +318,49 @@ if [[ ( $hour -eq 10 || $hour -eq 16 ) && $min -eq 0 ]]; then
 
 	# Seemed like a good idea at the time... ;-D
 	# if [[ $pct_log -gt 80 ]]; then
-	# 	echo "Error on ${host}: DASMOND Log is $pct_log% of Usage!"
-	# 	echo "   $DASMOND_LOG $log_bytes ($log_hbytes)"
-	# 	exit -2
+	#	CHECK_ERROR_REPORTING
+	#	do_report="$?"
+	#	# Report Error...
+	#	if [[ $do_report == 1 ]]; then
+	#		echo -e -n "${NL}Error on ${host}:"
+	#		echo " DASMOND Log is $pct_log% of Usage!"
+	#		echo "   $DASMOND_LOG $log_bytes ($log_hbytes)"
+	#		NL="\n"
+	#	fi
+	#	# Set Error Count for Next Invocation,
+	#	if [[ ${ERROR_COUNT} -gt 0 ]]; then
+	#		SET_ERROR_COUNT
+	#	fi
+	#	exit -2
 	# fi
 
 	if [[ $pct_used -gt 80 ]]; then
-		echo "Error on ${host}: $dasmond_top_logdir is $pct_used% Full!"
-		echo "   $DASMOND_LOG $log_bytes ($log_hbytes)"
+
+		CHECK_ERROR_REPORTING
+		do_report="$?"
+
+		# Report Error...
+		if [[ $do_report == 1 ]]; then
+			echo -e -n "${NL}Error on ${host}:"
+			echo " $dasmond_top_logdir is $pct_used% Full!"
+			echo "   $DASMOND_LOG $log_bytes ($log_hbytes)"
+			NL="\n"
+		fi
+
+		# Set Error Count for Next Invocation,
+		if [[ ${ERROR_COUNT} -gt 0 ]]; then
+			SET_ERROR_COUNT
+		fi
+
 		exit -3
+
 	fi
+
+fi
+
+# Set Error Count for Next Invocation,
+if [[ ${ERROR_COUNT} -gt 0 ]]; then
+	SET_ERROR_COUNT
+	exit -4
 fi
 
