Improve Failure Mode/Spamming of DASMON Monitor 	- first off, actually try to create the logging sub-directory 	and touch the log files before we attempt to scribble into them 		-> extract $LOG_DIR for mkdir usage as needed 		-> only log failures once per hour (see below) 	- try to control spamming when things don't go well, especially 	for the case where we simply cannot access the Log File/Directory 	(like when we've gotten disconnected from the network, think 	"nED-on-Wheels"... ;-Q) 		-> choose a magic "SOS Minute" ($SOS_MIN) and reserve 		our whining to only occur during that minute (once per hour) 			=> move the extraction of $hour and $min to top... 		-> dump intended logs to stdout for cron to capture 	- It Works! :-D 		-> next we need to deal with some captured system state 		or counts _Between_ monitor invocations, to try and 		stem the tide of spam when something goes down... 			=> a nice exponential fall off would be nice... :-D

diff --git a/dasmon/server/dasmond_mon b/dasmon/server/dasmond_mon
--- a/dasmon/server/dasmond_mon
+++ b/dasmon/server/dasmond_mon
@@ -7,7 +7,7 @@
 #
 
 # Set Shared/External Mount Directory for Logging
-# LOG_HOME="/SNS/users/y8y"
+#LOG_HOME="/SNS/users/y8y"
 LOG_HOME="$HOME"
 
 host=`hostname`
@@ -16,8 +16,10 @@ host=`hostname`
 host_short=`echo $host | awk -F '.' '{print $1}'`
 #echo "host_short=$host_short"
 
-LOGFILE="$LOG_HOME/dasmond_mon/dasmond_mon.$host_short.log"
-LOGLOGFILE="$LOG_HOME/dasmond_mon/dasmond_mon.$host_short-log.log"
+LOG_DIR="dasmond_mon"
+
+LOGFILE="${LOG_HOME}/${LOG_DIR}/dasmond_mon.$host_short.log"
+LOGLOGFILE="${LOG_HOME}/${LOG_DIR}/dasmond_mon.$host_short-log.log"
 
 DASMOND_USER="dasmon"
 DASMOND="/usr/sbin/dasmond"
@@ -27,6 +29,11 @@ DASMOND_LOG="/var/log/dasmond.log"
 PROG="dasmond_mon"
 
 TIME="/usr/bin/time" # for Test Harness, duh... ;-b
+
+# The Minute When We Gasp Our Dying Breath and Beg for Help... ;-D
+SOS_MIN=0
+
+NL=""
 
 #
 # Parse Command Line Options... ;-)
@@ -50,12 +57,21 @@ for arg in "$@" ; do
 
 done
 
-#
-# Get DASMOND process status...
-#
+# Get Date (and Hours/Minutes for Sub-Schedule Control...)
 
 date=`date`
 #echo "date=$date"
+
+hour=`echo $date | awk '{print $4}' | awk -F ":" '{print $1}' \
+	| sed 's/^0//g'`
+#echo "hour=$hour"
+min=`echo $date | awk '{print $4}' | awk -F ":" '{print $2}' \
+	| sed 's/^0//g'`
+#echo "min=$min"
+
+#
+# Get DASMOND process status...
+#
 
 status=`ps augxww | grep $DASMOND | grep -v -e $PROG -e $TIME -e grep \
 	| grep $DASMOND_USER`
@@ -109,27 +125,58 @@ log="$log time=$cpuT"
 # Dump DASMOND Status Snapshot into Log file...
 #
 
-echo -e "$log" >> $LOGFILE
+# If Log Sub-Directory Doesn't Exist, Try to Create It... ;-D
+if [[ ! -d "${LOG_HOME}/${LOG_DIR}" ]]; then
+
+	ckd=`mkdir -p "${LOG_HOME}/${LOG_DIR}" 2>&1`
+
+	# Only Whine Once Per Hour If There's No Log Sub-Directory
+	# (And We Can't Create It...)
+	if [[ $? != 0 && $min -eq ${SOS_MIN} ]]; then
+		echo -e "${NL}Error Creating DASMON Monitor Log Sub-Directory!"
+		echo -e "\n${ckd}"
+		NL="\n"
+	fi
+
+fi
+
+# If Log File Doesn't Exist, Try to Create It... ;-D
+if [[ ! -e "${LOGFILE}" ]]; then
+
+	ckt=`touch "${LOGFILE}" 2>&1`
+
+	# Only Whine Once Per Hour If There's No Log File
+	# (And We Can't Create It...)
+	if [[ $? != 0 && $min -eq ${SOS_MIN} ]]; then
+		echo -e "${NL}Error Creating DASMON Monitor Log File!"
+		echo -e "\n${ckt}"
+		NL="\n"
+	fi
+
+fi
+
+if [[ -w "${LOGFILE}" ]]; then
+
+	echo -e "$log" >> ${LOGFILE}
+
+# Only Whine Once Per Hour If We've Become Disconnected from the Universe...
+elif [[ $min -eq ${SOS_MIN} ]]; then
+
+	echo -e "${NL}Error: DASMON Monitor Log File Unwritable!"
+	echo -e "\n$log"
+	NL="\n"
+
+fi
 
 #
 # Check on the DASMOND Log File size/usage...
 #
-
-hour=`echo $date | awk '{print $4}' | awk -F ":" '{print $1}' \
-	| sed 's/^0//g'`
-#echo "hour=$hour"
-min=`echo $date | awk '{print $4}' | awk -F ":" '{print $2}' \
-	| sed 's/^0//g'`
-#echo "min=$min"
 
 # Only check once or twice per day maybe...?
 if [[ ( $hour -eq 10 || $hour -eq 16 ) && $min -eq 0 ]]; then
 
 	log_bytes=`/bin/ls -l $DASMOND_LOG | awk '{print $5}'`
 	log_hbytes=`/bin/ls -lh $DASMOND_LOG | awk '{print $5}'`
-
-	touch $LOGLOGFILE
-	echo "$date $host $DASMOND_LOG = $log_hbytes" >> $LOGLOGFILE
 
 	dasmond_top_logdir=`echo $DASMOND_LOG | awk -F '/' '{print "/"$2}'`
 
@@ -144,9 +191,43 @@ if [[ ( $hour -eq 10 || $hour -eq 16 ) && $min -eq 0 ]]; then
 	pct_used=$(( $log_used * 100 / $log_total ))
 	#echo "pct_used=$pct_used"
 
-	echo \
-	"   Log is $log_bytes = $pct_log% of usage, Disk is $pct_used% full." \
-		>> $LOGLOGFILE
+	# If Log Log File Doesn't Exist, Try to Create It... ;-D
+	if [[ ! -e "${LOGLOGFILE}" ]]; then
+
+		ckt=`touch "${LOGLOGFILE}" 2>&1`
+
+		# Only Whine Once Per Hour If There's No Log Log File
+		# (And We Can't Create It...)
+		if [[ $? != 0 && $min -eq ${SOS_MIN} ]]; then
+			echo -e "${NL}Error Creating DASMON Monitor Log Log File!"
+			echo -e "\n${ckt}"
+			NL="\n"
+		fi
+
+	fi
+
+	if [[ -w "${LOGLOGFILE}" ]]; then
+
+		echo "$date $host $DASMOND_LOG = $log_hbytes" >> ${LOGLOGFILE}
+
+		echo -n "   Log is $log_bytes = $pct_log% of usage," \
+			>> ${LOGLOGFILE}
+		echo " Disk is $pct_used% full." >> ${LOGLOGFILE}
+
+	# Only Whine Once Per Hour If We've Become
+	# Disconnected from the Universe...
+	elif [[ $min -eq ${SOS_MIN} ]]; then
+
+		echo -e "${NL}Error: DASMON Monitor Log Log File Unwritable!"
+
+		echo "\n$date $host $DASMOND_LOG = $log_hbytes"
+
+		echo -n "   Log is $log_bytes = $pct_log% of usage,"
+		echo " Disk is $pct_used% full."
+
+		NL="\n"
+
+	fi
 
 	# Seemed like a good idea at the time... ;-D
 	# if [[ $pct_log -gt 80 ]]; then
